# Generated by Django 4.2.5 on 2024-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('SCIFI', 'Science Fiction'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('MUSICAL', 'Musical'), ('DOCU', 'Documentary'), ('ANIMATION', 'Animation'), ('THRILLER', 'Thriller'), ('FANTASY', 'Fantasy')], max_length=50)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
