# Generated by Django 5.0.2 on 2024-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_description_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='This movie is missing a description', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='MoviePosterExample.jpg', upload_to='posters'),
        ),
    ]
