# Generated by Django 4.2.5 on 2024-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_description_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
