# Generated by Django 4.2.5 on 2024-03-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite',
        ),
        migrations.AddField(
            model_name='rating',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
