# Generated by Django 5.0.2 on 2024-03-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_favorite_rating_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': 'id'},
        ),
    ]
