# Generated by Django 5.0.2 on 2024-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_rating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('SCIFI', 'Science Fiction'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('MUSICAL', 'Musical'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation'), ('THRILLER', 'Thriller'), ('FANTASY', 'Fantasy')], max_length=50),
        ),
    ]
